/*
 * Copyright 2015 Tom Gibara
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package com.tomgibara.tries.nodes;

import com.tomgibara.streams.StreamDeserializer;
import com.tomgibara.tries.ByteOrder;
import com.tomgibara.tries.Trie;
import com.tomgibara.tries.Tries;

/**
 * <p>
 * A source of {@link TrieNodes}. Sources are supplied to {@link Tries} via the
 * {@link Tries#nodeSource(TrieNodeSource)} method to control how nodes are
 * managed for {@link Trie} instances it creates.
 * 
 * <p>
 * The interface also defines a number of 'standard' implementations that are
 * optimized for different scenarios. Other than their convenient availability
 * as part of this package, they are not distinguished from alternatively
 * defined sources that may better suite some applications.
 * 
 * @author Tom Gibara
 * @see TrieNodes
 * @see Tries
 */

public interface TrieNodeSource  {

	/**
	 * Whether the node source supports counting.
	 * 
	 * @return true if node counting is supported, false otherwise
	 */

	boolean isCountingSupported();

	/**
	 * Creates a new empty node structure.
	 * 
	 * @param byteOrder
	 *            the ordering to be applied to a node's direct descendants
	 * @param counting
	 *            whether the nodes are expected to provide efficient descendent
	 *            counts
	 * @param capacityHint
	 *            hints at the number of nodes the trie may grow to contain
	 * @return an empty tree of nodes
	 */

	TrieNodes newNodes(ByteOrder byteOrder, boolean counting, int capacityHint);
	
	/**
	 * Copies the nodes from an existing {@link TrieNodes} instance. The byte
	 * order on the supplied nodes determines the byte order of the returned
	 * nodes. The implementation of this method cannot generally assume that the
	 * nodes passed in originate from the same {@link TrieNodeSource}.
	 * 
	 * @param nodes
	 *            the nodes to duplicate
	 * @param counting
	 *            whether the duplicated nodes are expected to provide efficient
	 *            descendent counts
	 * @param capacityHint
	 *            hints at the number of nodes the trie may grow to contain
	 * @return a copy of the supplied nodes
	 */
	
	TrieNodes copyNodes(TrieNodes nodes, boolean counting, int capacityHint);

	/**
	 * Provides an object that can deserialize the data generated by
	 * {@link TrieNodePath#writeTo(com.tomgibara.streams.WriteStream)} into a
	 * new tree.
	 * 
	 * @param byteOrder
	 *            the byte order that was applied to the serialization
	 * @param counting
	 *            whether the reconstructed nodes are expected to provide
	 *            efficient descendent counts
	 * @param capacityHint
	 *            hints at the number of nodes the trie may grow to contain
	 * @return a tree of nodes restored from a byte stream
	 */

	StreamDeserializer<TrieNodes> deserializer(ByteOrder byteOrder, boolean counting, int capacityHint);
}
